### ISSUE TITLE
server side rendering - window is not defined

### ISSUE THREAD

**Issue by dsbert** [jrainlau/vue-flatpickr#39]
I'm at attempting to integrate `vue-flatpickr` into a project based on the server-side rendering example provided at [vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0). I'm getting the following error. Is there a work-around for this?

```js
// app.js
import Vue from 'vue';
import VueFlatpickr from 'vue-flatpickr'

Vue.use(VueFlatpickr);
```

```html
<!-- App.vue -->

<div><Flatpickr /></div>
```

```
ReferenceError: window is not defined
    at Object.<anonymous> (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:3:1814)
    at t (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:382)
    at Object.<anonymous> (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:3:7249)
    at t (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:382)
    at Object.e.exports.render.e (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:1784)
    at t (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:382)
    at Object.e.exports.version (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:627)
    at t (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:382)
    at e.__esModule.default (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:470)
    at d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:475
    at n (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:143)
    at Object.<anonymous> (d:\code\budget2\node_modules\vue-flatpickr\dist\index.js:1:253)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by JChehe** [comment]
@dsbert Hello, I also encountered the same problem, did you solve it?

**Comment by dsbert** [comment]
@JChehe No. You will probably need to do something to fake the global window object prior to importing flatpickr.

I ended up switching to a serverless architecture.
